vich_uploader:
    db_driver: orm

    mappings:
        dog_images:
           uri_prefix: /images/dogs
           upload_destination: '%kernel.project_dir%/public/images/dogs'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # permet d'obtenir des noms uniques pour les images
