vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        chien_images:
           uri_prefix: /images/chiens
           upload_destination: '%kernel.project_dir%/public/images/chiens'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # permet d'obtenir des noms uniques pour les images
